{% set version = "1.0.7" %}

package:
  name: pymsgbox
  version: {{ version }}

source:
  fn: PyMsgBox-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/P/PyMsgBox/PyMsgBox-{{ version }}.tar.gz
  sha256: 7df5ed66c8a80fd36b83b278ba164e7a1d135c8fb8bdf38b291e46bf31d28085

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pymsgbox

about:
  home: https://github.com/asweigart/PyMsgBox
  license: BSD 3-Clause
  license_family: BSD
  summary: A simple, cross-platform, pure Python module for JavaScript-like message boxes.

extra:
  recipe-maintainers:
    - jschueller
