{% set version = "1.0.9" %}

package:
  name: pymsgbox
  version: {{ version }}

source:
  fn: PyMsgBox-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/P/PyMsgBox/PyMsgBox-{{ version }}.tar.gz
  sha256: 2194227de8bff7a3d6da541848705a155dcbb2a06ee120d9f280a1d7f51263ff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - pymsgbox

about:
  home: https://github.com/asweigart/PyMsgBox
  license: BSD 3-Clause
  license_family: BSD
  summary: A simple, cross-platform, pure Python module for JavaScript-like message boxes.

extra:
  recipe-maintainers:
    - jschueller
