travis:
  secure:
    BINSTAR_TOKEN: kB1QSmdAORafcTetrUCFaoUGZ1kVmvq3xGZ57cLMXv3hz5j30tlsrYF1gI104NsGEsoGeDGliGWjr/hds5OdRMzZ2j+wyHTA79SKpPWje+iFYousEnRkPZKFnW4REpOzLqUe7h9tpo4Rd/HfbArIbm9o92v48EnceNGwZnZ0fX9DqHOOLhEPzb5V54xLD0Tw/p9zgkKD+OPkCsiA1dlJRqiRhtGU4fSmq7dKhGOfyJUn5gvySLwAH+Me7xMLB3MSLNMt+NbU2BQmzYRKI8DPApKpWKBQe5InDbbIOnGRBRje/Zvp106OZ9tWzhaOIZFO4pFTAD9ga0vHwSJuvLHmg+M0wTyXkjDJr4rJiyU++re7WsNjZnl73HW/jv1pl/UiFVUh2XkkvKSW1CIrSmYWFmvZRBnUZAwnUdfO8r9gwK3pmT7ra0oVZ8m6tagIJIzB8/PoqypZHmQmoPtbBmVZgApL/kC98L3yw1zPHlf233BmUR3F+Xd8iUwy4r+HSio5FoJm7YHCWZfzRmAsOYH23QDCLa4gctVPf9rMRJoaiJQaMBiNEEOEMGiafazg+Hwq1tMvgaiXzh6WajD9Jba3WnVZQXgbICpBFpuO6ibBw4m1gbh1QY+lcRnYsk+pAY8d1VYa1kgw2PB6hhZoMR6o4CblhbGhQpkMD5i8Gynpe6A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
