travis:
  secure:
    BINSTAR_TOKEN: g+shGcyEj+g5CMRqwQ/Nc+hE1IhCTsorXwS8OqHoKcqss1a/UlhIOAGyM3GnflHyX064sQcfRp92TC2UOn8EZqjXVT1l1mJeHqM5bGohzRQSZZrQmf7UDxV+PS6x0AofiDzE2P78bLmZuulalhxS4OC+EdXrOjEAzxHfodCwM06c5+nA5LjdPzNywYhvZ5HVd0SuJP6v5AJ9q0J/0pdBcGHjEf4XXmzA5N5stKStRjtDIzgNn48nfzFttCAg0Ux5j2abpX9O61bpM+iyzE7shIIZ5lGx/dNH8DhG0OEADWtydCjsmxbEjqLhCsodF9HlBZ4g7/jP6AZxUD/bZjUrvApg5GgwGk8KsoBQiBWYuK/3f9sYk0J8zoWd5J8MZsK1fk9O2As0MPF9DBfBl6TmVyLtumM3eHcm8a1AXOqD+r0JScY6GBu2mqYw+l1JVKBIvWflodFjPd+yqv6LLLxPj9XU6gfRMp3oORlvh07oRL3iTNtb/FP0OEsY7sHgJcU+QLu0djxP9H/oU/mOmSTEhXA9tWEtJcm6UljfEPNhZbScSeYiGlavmly2793PeA9KvA7gcPoRSY4R80TteG4LnMN/R7HUOyiUCpIWWCaeDkzgzb2Jlp/Cf3PmeanF2ObnOnGGGO4wJ/zb/mmWML8txLlYjalBFz37iTElu93vZdw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
